import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {
  Box,
  Button,
  Container,
  Skeleton,
  Text,
  Textarea,
} from '@chakra-ui/react'
import { useRef, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isLoading, setIsLoading] = useState(false)
  const [chatSession, setChatSession] = useState<string[]>([])
  const chatInput = useRef<HTMLTextAreaElement>(null)
  const getChatResponse = async () => {
    setIsLoading(true)
    const chatInputValue = chatInput.current?.value
    if (!chatInputValue) return
    const response = await fetch('/api/chat', {
      method: 'POST',
      body: JSON.stringify({ message: chatInputValue }),
      headers: {
        'Content-Type': 'application/json',
      },
    })
    console.log(response)
    const data = await response.json()
    console.log(data)
    setChatSession((prev) => [...prev, data.message])
  }
  return (
    <>
      <Head>
        <title>AI Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {chatSession ? (
          <Box>
            {isLoading ? (
              <>
                <Skeleton height="20px" />
                <Skeleton height="20px" />
              </>
            ) : (
              chatSession.map((message, index) => (
                <Text key={index}>{message}</Text>
              ))
            )}
          </Box>
        ) : null}
        <Textarea ref={chatInput} />
        <Button onClick={() => getChatResponse()}>Submit</Button>
      </Container>
    </>
  )
}
